import './globals.css'
import { Inter } from 'next/font/google'
import "../styles/global.scss";


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Handphone Spesifikasi',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>{children}</body>
    </html>
  )
}
