import Homepage from '../views/Home/Homepage';

export const metadata = {
  title: 'Handphone Spesifikasi',
  description: 'Generated by create next app',
}
const Home = () => {
  return (
    <>
      <Homepage />
    </>
  )
}

export default Home;