import Shared from '@/components/Shared'
import Gallery from "@/views/Gallery/Gallery";


export const metadata = {
    title: 'Gale Handphone Spesifikasi',
    description: 'Generated by create next app',
}
const pageGallery = (props) => {

    return (
        <>
            <Gallery />
        </>
    )
}

export default pageGallery