import ProductView from "@/views/ProductView/ProductView";


export const metadata = {
    title: 'Product - Handphone Spesifikasi',
    description: 'Generated by create next app',
}
const product = (props) => {
    return (
        <>
            <ProductView />
        </>
    )
}

export default product